Repository rtsc8/hostal_donde_las_paisas, pull requests merged in 2019-07, with the labels that each got.

#44 bugfix/carrousel-landing
  css/home.css
  css/style.css
  index.html
Labels: Carrousel, Hero, Update, bug

#41 feature/buttons-size
  css/style.css
  index.html
Labels: Homepage, Update, gallery

#56 feature/map-component
  css/contact.css
  pages/contact.html
Labels: contact

#57 bugfix/carrousel-margin
  css/style.css
Labels: Carrousel, bug

#51 Feature/navbar-footer
  css/style.css
  index.html
  pages/contact.html
  pages/gallery.html
  pages/quote.html
Labels: Update, contact, gallery, quote

#59 general/footer-info
  index.html
  pages/contact.html
  pages/gallery.html
  pages/quote.html
Labels: Homepage, Update, contact, gallery, quote

#61 Page prelaunch
  README.md
  css/contact.css
  css/gallery.css
  css/home.css
  css/style.css
  index.html
  pages/contact.html
  pages/gallery.html
  pages/quote.html
Labels: Update

#58 Home/quote button
  css/home.css
  index.html
Labels: Homepage, Update, quote

#65 quote/button-distance
  css/home.css
Labels: Homepage, bug

#45 Feature/quote form
  assets/icons/calendar.svg
  assets/icons/color-white.svg
  assets/icons/warning.svg
  css/quotes.css
  css/style.css
  index.html
  js/consts.js
  js/quote_tool.js
  js/quoting_readme.md
  pages/contact.html
  pages/quote.html
Labels: Quote view update, quote

#70 Navbar mobile behaviour and logo visibility fix.
  css/style.css
  js/main_nav.js
Labels: bug
