Repository rtsc8/hostal_donde_las_paisas, pull requests merged in 2019-05, with the labels that each got.

#18 feature/services-section: Section Services
  .gitignore
  assets/icons/services/cooking.svg
  assets/icons/services/reception.svg
  assets/icons/services/sunset.svg
  css/home.css
  css/style.css
  index.html
Labels: Homepage

#27 fix/comodities-section-padding
  css/home.css
  css/style.css
Labels: enhancement

#21 Updated button component
  css/style.css
Labels: Tools
